### PR TITLE
fix(client): Fix the required check.

### LINKED ISSUE #231: `required` check does not check empty objects correctly
@philbooth noticed this while reviewing https://github.com/mozilla/fxa-content-server/issues/4586. 

[required has the following code](https://github.com/mozilla/fxa-js-client/blob/9a0b30c5531dbafe703d8388320eedc416e8706e/client/FxAccountClient.js#L20):

```js
function required(val, name) {
    if (!val || val === {}) {
      throw new Error('Missing ' + name);
    }
}
```

In particular `val === {}`. This will *never* be true, even if passing in an empty object.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
It didn't allow falsey values, and checked incorrectly for empty objects.

fixes #231

@philbooth - r?

### CODE REVIEW

File: client/FxAccountClient.js [hunk 1]
```diff
@@ -16,8 +16,31 @@ define([
...
+  function toString(val) {
+    return Object.prototype.toString.call(val);
+  }
+
+  function isEmptyObject(val) {
+    return toString(val) === '[object Object]' && ! Object.keys(val).length;
+  }
+
+  function isEmptyString(val) {
+    return toString(val) === '[object String]' && ! val.length;
```
Comment (philbooth) [inline client/FxAccountClient.js]: Couldn't this one just be:

```js
  return val === '';
```

?

Comment (shane-tomlinson) [inline client/FxAccountClient.js]: Yes, it could

**Comment by philbooth** [comment]
👍 r+
