### PR TITLE
fix(tests): remove account devices, add unlock verify code

### LINKED ISSUE #151: `npm run test-local` test failures
```
group: devices
Waiting for email...
FAIL: #get (88ms)
AssertionError: expected { Object (code, errno, ...) } to be falsy
    at assert.notOk (/Users/stomlinson/development/fxa-js-client/node_modules/intern-geezer/assert.js:529:10)
    at onSettled (/Users/stomlinson/development/fxa-js-client/components/p/p.js:258:10)
    at onTick (/Users/stomlinson/development/fxa-js-client/components/p/p.js:40:4)
    at process._tickCallback (node.js:419:13)
0/1 tests passed
groupEnd: devices
```

...

```
FAIL: #accountUnlockVerifyCode (2ms)
AssertionError: expected { Object (code, errno, ...) } to be falsy
    at assert.notOk (/Users/stomlinson/development/fxa-js-client/node_modules/intern-geezer/assert.js:529:10)
    at onSettled (/Users/stomlinson/development/fxa-js-client/components/p/p.js:258:10)
    at onTick (/Users/stomlinson/development/fxa-js-client/components/p/p.js:40:4)
    at process._tickCallback (node.js:419:13)
PASS: #accountUnlockVerifyCode with no uid (1ms)
PASS: #accountUnlockVerifyCode with no code (0ms)
19/20 tests passed
```

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #151 

@shane-tomlinson r?

### CODE REVIEW

**Comment by vladikoff** [comment]
ping @shane-tomlinson  :smile:

**Comment by shane-tomlinson** [comment]
> ping @shane-tomlinson :smile:

DOH.

File: tests/lib/account.js [hunk 1]
```diff
@@ -354,6 +355,7 @@ define([
       });
 
       test('#accountUnlockResendCode', function () {
+        var account;
```
Comment (shane-tomlinson) [inline tests/lib/account.js]: huh, jshint/lint didn't catch these?
