### PR TITLE
fix(client): remove redundant metrics context data

### LINKED ISSUE #216: Stop sending all of the metricsContext data to the back-end
We don't need to emit all of the `metricsContext` data with every event, now that it is correctly emitted from the content server flow events. We only need to send the `flowId` and the `flowBeginTime` really.

### PR DESCRIPTION
**Pull request by philbooth**
Fixes #216.

The flow data is modelled as `flow_event` and `flow_metadata` tables in redshift, which are joined on `flowId`. All of the interesting properties are stored in `flow_metadata`, so we don't actually need to pass them round everywhere and emit them from every event. As long as they are present on the begin event, which they are as of mozilla/fxa-content-server#4234, the import scripts will populate the `flow_metadata` table correctly.

This change stops sending most of those properties to endpoints that accept metrics context data. We still need to send `flowId` and `flowBeginTime`.

@shane-tomlinson, last one for this morning I promise, r?

### CODE REVIEW

File: tests/all.js [hunk 1]
```diff
@@ -3,23 +3,24 @@
...
-  'tests/lib/errors',
-  'tests/lib/headerLang',
+  'tests/lib/request',
+  'tests/lib/session',
+  'tests/lib/signIn',
+  'tests/lib/signUp',
+  'tests/lib/unbundle',
   'tests/lib/uriVersion',
-  'tests/lib/device'
+  'tests/lib/verifyCode'
```
Comment (philbooth) [inline tests/all.js]: I took the liberty of re-ordering these as I felt like a short enough array to be reviewable and left things much easier to manage in the future. The added item is `'tests/lib/metricsContext'`, obviously.
